let repos =[
    {
        "id": 296759533,
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTY3NTk1MzM=",
        "name": "lab3",
        "full_name": "chrismon88/lab3",
        "private": false,
        "owner": {
            "login": "chrismon88",
            "id": 59941792,
            "node_id": "MDQ6VXNlcjU5OTQxNzky",
            "avatar_url": "https://avatars3.githubusercontent.com/u/59941792?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/chrismon88",
            "html_url": "https://github.com/chrismon88",
            "followers_url": "https://api.github.com/users/chrismon88/followers",
            "following_url": "https://api.github.com/users/chrismon88/following{/other_user}",
            "gists_url": "https://api.github.com/users/chrismon88/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/chrismon88/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/chrismon88/subscriptions",
            "organizations_url": "https://api.github.com/users/chrismon88/orgs",
            "repos_url": "https://api.github.com/users/chrismon88/repos",
            "events_url": "https://api.github.com/users/chrismon88/events{/privacy}",
            "received_events_url": "https://api.github.com/users/chrismon88/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/chrismon88/lab3",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/chrismon88/lab3",
        "forks_url": "https://api.github.com/repos/chrismon88/lab3/forks",
        "keys_url": "https://api.github.com/repos/chrismon88/lab3/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/chrismon88/lab3/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/chrismon88/lab3/teams",
        "hooks_url": "https://api.github.com/repos/chrismon88/lab3/hooks",
        "issue_events_url": "https://api.github.com/repos/chrismon88/lab3/issues/events{/number}",
        "events_url": "https://api.github.com/repos/chrismon88/lab3/events",
        "assignees_url": "https://api.github.com/repos/chrismon88/lab3/assignees{/user}",
        "branches_url": "https://api.github.com/repos/chrismon88/lab3/branches{/branch}",
        "tags_url": "https://api.github.com/repos/chrismon88/lab3/tags",
        "blobs_url": "https://api.github.com/repos/chrismon88/lab3/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/chrismon88/lab3/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/chrismon88/lab3/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/chrismon88/lab3/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/chrismon88/lab3/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/chrismon88/lab3/languages",
        "stargazers_url": "https://api.github.com/repos/chrismon88/lab3/stargazers",
        "contributors_url": "https://api.github.com/repos/chrismon88/lab3/contributors",
        "subscribers_url": "https://api.github.com/repos/chrismon88/lab3/subscribers",
        "subscription_url": "https://api.github.com/repos/chrismon88/lab3/subscription",
        "commits_url": "https://api.github.com/repos/chrismon88/lab3/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/chrismon88/lab3/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/chrismon88/lab3/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/chrismon88/lab3/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/chrismon88/lab3/contents/{+path}",
        "compare_url": "https://api.github.com/repos/chrismon88/lab3/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/chrismon88/lab3/merges",
        "archive_url": "https://api.github.com/repos/chrismon88/lab3/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/chrismon88/lab3/downloads",
        "issues_url": "https://api.github.com/repos/chrismon88/lab3/issues{/number}",
        "pulls_url": "https://api.github.com/repos/chrismon88/lab3/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/chrismon88/lab3/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/chrismon88/lab3/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/chrismon88/lab3/labels{/name}",
        "releases_url": "https://api.github.com/repos/chrismon88/lab3/releases{/id}",
        "deployments_url": "https://api.github.com/repos/chrismon88/lab3/deployments",
        "created_at": "2020-09-19T00:56:52Z",
        "updated_at": "2020-09-19T00:57:07Z",
        "pushed_at": "2020-09-19T00:57:05Z",
        "git_url": "git://github.com/chrismon88/lab3.git",
        "ssh_url": "git@github.com:chrismon88/lab3.git",
        "clone_url": "https://github.com/chrismon88/lab3.git",
        "svn_url": "https://github.com/chrismon88/lab3",
        "homepage": null,
        "size": 4,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 292073055,
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTIwNzMwNTU=",
        "name": "week_1",
        "full_name": "chrismon88/week_1",
        "private": false,
        "owner": {
            "login": "chrismon88",
            "id": 59941792,
            "node_id": "MDQ6VXNlcjU5OTQxNzky",
            "avatar_url": "https://avatars3.githubusercontent.com/u/59941792?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/chrismon88",
            "html_url": "https://github.com/chrismon88",
            "followers_url": "https://api.github.com/users/chrismon88/followers",
            "following_url": "https://api.github.com/users/chrismon88/following{/other_user}",
            "gists_url": "https://api.github.com/users/chrismon88/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/chrismon88/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/chrismon88/subscriptions",
            "organizations_url": "https://api.github.com/users/chrismon88/orgs",
            "repos_url": "https://api.github.com/users/chrismon88/repos",
            "events_url": "https://api.github.com/users/chrismon88/events{/privacy}",
            "received_events_url": "https://api.github.com/users/chrismon88/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/chrismon88/week_1",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/chrismon88/week_1",
        "forks_url": "https://api.github.com/repos/chrismon88/week_1/forks",
        "keys_url": "https://api.github.com/repos/chrismon88/week_1/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/chrismon88/week_1/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/chrismon88/week_1/teams",
        "hooks_url": "https://api.github.com/repos/chrismon88/week_1/hooks",
        "issue_events_url": "https://api.github.com/repos/chrismon88/week_1/issues/events{/number}",
        "events_url": "https://api.github.com/repos/chrismon88/week_1/events",
        "assignees_url": "https://api.github.com/repos/chrismon88/week_1/assignees{/user}",
        "branches_url": "https://api.github.com/repos/chrismon88/week_1/branches{/branch}",
        "tags_url": "https://api.github.com/repos/chrismon88/week_1/tags",
        "blobs_url": "https://api.github.com/repos/chrismon88/week_1/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/chrismon88/week_1/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/chrismon88/week_1/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/chrismon88/week_1/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/chrismon88/week_1/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/chrismon88/week_1/languages",
        "stargazers_url": "https://api.github.com/repos/chrismon88/week_1/stargazers",
        "contributors_url": "https://api.github.com/repos/chrismon88/week_1/contributors",
        "subscribers_url": "https://api.github.com/repos/chrismon88/week_1/subscribers",
        "subscription_url": "https://api.github.com/repos/chrismon88/week_1/subscription",
        "commits_url": "https://api.github.com/repos/chrismon88/week_1/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/chrismon88/week_1/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/chrismon88/week_1/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/chrismon88/week_1/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/chrismon88/week_1/contents/{+path}",
        "compare_url": "https://api.github.com/repos/chrismon88/week_1/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/chrismon88/week_1/merges",
        "archive_url": "https://api.github.com/repos/chrismon88/week_1/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/chrismon88/week_1/downloads",
        "issues_url": "https://api.github.com/repos/chrismon88/week_1/issues{/number}",
        "pulls_url": "https://api.github.com/repos/chrismon88/week_1/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/chrismon88/week_1/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/chrismon88/week_1/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/chrismon88/week_1/labels{/name}",
        "releases_url": "https://api.github.com/repos/chrismon88/week_1/releases{/id}",
        "deployments_url": "https://api.github.com/repos/chrismon88/week_1/deployments",
        "created_at": "2020-09-01T18:12:06Z",
        "updated_at": "2020-09-08T19:37:51Z",
        "pushed_at": "2020-09-08T19:37:48Z",
        "git_url": "git://github.com/chrismon88/week_1.git",
        "ssh_url": "git@github.com:chrismon88/week_1.git",
        "clone_url": "https://github.com/chrismon88/week_1.git",
        "svn_url": "https://github.com/chrismon88/week_1",
        "homepage": null,
        "size": 5010,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    }
]
// print name of repositories?
// print language of each repository

repos.forEach(function( repo) {
    console.log(repo.name, repo.language)
})
// count the number of repositories in each language
// include a count for repositories without a language
// store the counts in a new object.


languageCounts = {}

repos.forEach(function (repo){
    let language = repo.language
    console.log(language)
    if (languageCounts [language] !== undefined) {
        let count = languageCounts[language]
        count++
        languageCounts[language] = count
    } else {
        languageCounts[language] = 1
    }
})

console.log(languageCounts)

